# Generated by Django 2.2.14 on 2021-07-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210712_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rerence_user',
            new_name='Refrence_user',
        ),
    ]
